name: eve
favicon: null
layout_spectrum: 0.08731385786086321
typography_spectrum: 0.6069927003700286
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3583779155742377
  lightness: 0.6262506588827819
  saturation: 0.30964952055364847
  rhythmicContrast: 0.3470588093623519
purpose: []
